### ISSUE TITLE
Low reported results.

### ISSUE THREAD

**Issue by tzjtatata** [caoyunkang/WinClip#1]
Thank you for re-implementation. But, why the results you report is far lower than original paper?

**Comment by caoyunkang** [comment]
> Thank you for re-implementation. But, why the results you report is far lower than original paper?
> 

Hi! I must admit that the reported results are lower than reported. I would be greatly appreciated if you could help me with improvements.

**Comment by tzjtatata** [comment]
Do you have any guess about the reason?

**Comment by BenjiKCF** [comment]
I saw that you use softmax in your normality and abnormality score function. The paper didnt state how did they calculate it. But since they calculated the one-class anomlay score as -<f(x), g(s-)> (Section 4.1),  I guess the anomaly score is sigmoid(-<f(x), g(s+)>-<f(x), g(s-)>), what do you think?

**Comment by sjw821** [comment]
In the original paper, the anomaly score is directly calculated from the image token and text embedding in the case of image-level anomaly classification.
Meanwhile, in this code, anomaly score is calculated by using the max value from pixel-level prediction. This may be the reason for the differences in results.
